apiVersion: v1
kind: Service
metadata:
  name: svc-rabbitmq
  namespace: tech-challenge
  labels:
    app: rabbitmq
    component: tools
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
