apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: tech-challenge
  labels:
    app: grafana
    component: tools
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
