apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-gateway
  namespace: tech-challenge
  labels:
    app: gateway
    component: app
  annotations:
    description: "Exposes internal app endpoints"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        component: app
    spec:
      containers:
        - name: gateway
          image: local_gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
