apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-query
  namespace: tech-challenge
  labels:
    app: query
    component: function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: local_query:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-sqlserver
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: AzureWebJobsStorage
              value: "UseDevelopmentStorage=true"
