apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-commands
  namespace: tech-challenge
  labels:
    app: commands
    component: app
  annotations:
    description: "API to receive write operations"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands
  template:
    metadata:
      labels:
        app: commands
        component: app
    spec:
      containers:
        - name: commands
          image: local_commands:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config-rabbitmq
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
