apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq
  namespace: tech-challenge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rabbitmq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-rabbitmq
                port:
                  number: 15672
