# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.sln .
COPY src/NetArchTechChallenge.Persistence/*.csproj NetArchTechChallenge.Persistence/
COPY src/NetArchTechChallenge.Shared.*/*.csproj ./
RUN dotnet restore NetArchTechChallenge.Persistence/NetArchTechChallenge.Persistence.csproj
COPY src/. .
WORKDIR /src/NetArchTechChallenge.Persistence
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 9091
ENTRYPOINT ["dotnet", "NetArchTechChallenge.Persistence.dll"]