global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'commands'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['commands:8080']

  - job_name: 'persistence'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['persistence:9091']

  - job_name: 'query'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['query:7071']

  - job_name: 'dlqmonitor'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['dlqmonitor:7072']