apiVersion: v1
kind: ConfigMap
metadata:
  name: config-prometheus
  namespace: tech-challenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'apps'
        metrics_path: /api/metrics
        static_configs:
          - targets:
            - svc-commands:8080
            - svc-persistence:9091
            - svc-query:80
            - svc-dlqmonitor:80