apiVersion: v1
kind: Service
metadata:
  name: svc-gateway
  namespace: tech-challenge
  labels:
    app: gateway
    component: app
  annotations:
    description: "Exposes internal app endpoints"
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
