apiVersion: v1
kind: Service
metadata:
  name: svc-query
  namespace: tech-challenge
  labels:
    app: query
    component: app
spec:
  selector:
    app: query
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
