apiVersion: v1
kind: Service
metadata:
  name: svc-commands
  namespace: tech-challenge
  labels:
    app: commands
    component: api
spec:
  selector:
    app: commands
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
