name: Build Persistence

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'src/NetArchTechChallenge.Persistence/**'
      - 'src/NetArchTechChallenge.Shared.Domain/**'
      - 'src/NetArchTechChallenge.Shared.Application/**'
      - 'src/NetArchTechChallenge.Shared.Infrastructure/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'src/NetArchTechChallenge.Persistence/**'
      - 'src/NetArchTechChallenge.Shared.Domain/**'
      - 'src/NetArchTechChallenge.Shared.Application/**'
      - 'src/NetArchTechChallenge.Shared.Infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: dotnet build src/NetArchTechChallenge.Persistence/NetArchTechChallenge.Persistence.csproj --configuration Release

      - name: Run Tests (Unit and Integrated)
        run: dotnet test src/NetArchTechChallenge.Persistence.Tests/NetArchTechChallenge.Persistence.Tests.csproj --configuration Release
        continue-on-error: true
